version: '3'

services:
  db:
    image: mariadb
    container_name: database_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "store_stripe"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ../db:/var/lib/mysql